spring.application.name=PadelPro
springdoc.swagger-ui.path=/docs

# Base de datos
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.vketxcsgjfpbgrgxwopv
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Brevo API Key
brevo.api.key=${BREVO_API_KEY}

# Permitir peticiones desde Render (Spring Boot 4 lo requiere)
server.tomcat.allowed-host-headers=padelpro-tfg.onrender.com,localhost,127.0.0.1